apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: create-pr
spec:
  resources:
    inputs:
      - name: manifest-git
        type: git
  steps:
    - name: create-pr
      image: prontotools/alpine-git-curl
      script: |
        git clone $(resources.inputs.manifest-git.url)
        sed -i -e "20c\    tag: $(resources.inputs.manifest-git.revision)" ./alcatraz-manifests/helm/alcatraz-api/values.yaml
        sed -i -e "20c\    tag: $(resources.inputs.manifest-git.revision)" ./alcatraz-manifests/helm/alcatraz-ui/values.yaml
        cd ./alcatraz-manifests
        git config --global user.email "kohei.yamamoto919@gmail.com"
        git config --global user.name "yamagai"
        git add .
        git commit -m "Update image tags"
        git push origin main
        curl \
          -X POST \
          -H "Accept: application/vnd.github.v3+json" \
          https://api.github.com/repos/bamboooo-dev/alcatraz-manifests/pulls \
          -d '{"title":"Update image tags", "head":"main","base":"stable"}'
