apiVersion: tekton.dev/v1alpha1
kind: PipelineResource
metadata:
  name: manifest-git
spec:
  type: git
  params:
    - name: url
      value: https://github.com/bamboooo-dev/alcatraz-manifests.git
    - name: revision
      value: main
